name: Publish to PowerShell Gallery
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
  
  workflow_dispatch:
  
jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Publish to PowerShell Gallery
        run: |
          .\Publish.ps1 -apiKey ${{ secrets.POWERSHELLGALLERY }}